project:
  type: website
  output-dir: docs

website:
  title: "Python They Wrote: The HSMA Podcast"
  draft-mode: unlinked
  site-url: https://podcast.hsma.co.uk
  description: "The website of the HSMA Podcast 'Python They Wrote'"
  favicon: resources/favicon.png
  google-analytics:
    tracking-id: "G-7WCQBNMTC2"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  page-footer:
    center: |
      [![](/resources/ARC-logo-horizontal-white.svg){width=250px}](https://arc-swp.nihr.ac.uk/)<br/><br/>
      *This work is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West.
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
      <br/><br/>
      [Accessibility Statement](https://hsma.co.uk/policies_procedures/accessibility_statement)
      <br/>
      [Code of Conduct](https://hsma.co.uk/policies_procedures/code_of_conduct)
      <br/>
      [Concerns and Complaints](https://hsma.co.uk/policies_procedures/concerns_and_complaints)
  navbar:
    logo: "/resources/Chalky HSMA-07-wide white logo.png"
    title: false
    collapse-below: "xl"
    tools:
      - icon: globe2
        href: https://hsma.co.uk
      - icon: youtube
        href: https://www.youtube.com/@hsma
      - icon: github
        menu:
          - text: View the HSMA Github
            href:  https://github.com/hsma-programme
          - text: View the code for this website
            href:  https://github.com/hsma-programme/hsma_podcast_site
      - icon: envelope
        href: mailto:penchord@exeter.ac.uk?subject=Contact%20from%20HSMA%20Website%20&body=If%20you%20would%20like%20to%20be%20added%20to%20the%20HSMA%20mailing%20list%2C%20please%20complete%20the%20fields%20below.%0A%0AFull%20Name%3A%0A%0AOrganisation%3A%0A%0AIf%20you%20have%20a%20different%20query%2C%20please%20replace%20the%20content%20of%20this%20message%20with%20your%20own.%20%0A%0A\*\*This%20is%20an%20automatically%20generated%20email%20from%20a%20link%20on%20the%20HSMA%20website\*\*
      - icon: linkedin
        href: https://www.linkedin.com/company/hsma-programme/
    right:
      - href: index.qmd
        text: Welcome

      - href: episodes.qmd
        text: Episodes

      - text: "About"
        menu:
          - href: https://hsma.co.uk/about-hsma.html
            text: The HSMA Programme
          - href: https://hsma.co.uk/staff.html
            text: HSMA Staff
          - href: https://hsma.co.uk/foss.html
            text: HSMA & Open Source Software
          - href: https://hsma.co.uk/faqs.html
            text: Frequently Asked Questions
          - href: https://hsma.co.uk/policies_and_procedures.html
            text: Policies and Procedures


format:
  html:
    theme:
      - darkly
      - resources/style/theme-dark.scss
    css: resources/style/styles.css
    toc: true
    title-block-banner: /resources/banner.png
    mainfont: Lexend
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
